SELECT * FROM TB_CLIENTE_SP;

ALTER TABLE TB_CLIENTE_SP
ADD DataCriacao DATETIME2 DEFAULT GETDATE();

UPDATE TOP (1) TB_CLIENTE_SP SET DataCriacao = '2022-11-12 12: 13:40';

DELETE TOP(2) FROM TB_CLIENTE_SP;